version: "3.7"

services: 
    tsnode:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        volumes: 
            - ./src:/home/node/app/src
        container_name: tsnode
        expose: 
            - "4000"
        ports: 
            - "4000:4000"
        command: npm run dev